services:
  - type: web
    name: classreg
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: classreg-db
          property: connectionString

databases:
  - name: classreg-db
    databaseName: classreg
    user: classreg_user
    plan: free
